modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/HttpRafa/Modflared/issues"
license = "MIT"

[[mods]]
modId = "modflared"
version = "${version}"
displayName = "Modflared"
authors = "HttpRafa"
description = '''
Automatically connects you to a Cloudflare tunnel without having to install cloudflared separately.
'''
#logoFile = ""

[[dependencies.modflared]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.modflared]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.modflared]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.93,)"
ordering = "AFTER"
side = "CLIENT"
